#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UITesting.Resource", IsApplication=true)]

namespace UITesting
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_fitness_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_food_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_social_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_tips_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_directions_bike = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_group = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_kitchen = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_pregnant_woman = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_room = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_settings_black_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int newborn = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000d
			public const int ChangeUsernameText = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int SaveSettings = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int Settings_button = 2131230740;
			
			// aapt resource value: 0x7f080001
			public const int adviceListView = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int adviceTextText = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int adviceTitleText = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int adviseButton = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int discText = 2131230737;
			
			// aapt resource value: 0x7f08000a
			public const int foodButton = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int imageView1 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int kmText = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int pointText = 2131230736;
			
			// aapt resource value: 0x7f080009
			public const int runButton = 2131230729;
			
			// aapt resource value: 0x7f080004
			public const int scoreText = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int stepsText = 2131230728;
			
			// aapt resource value: 0x7f080013
			public const int taskListView = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int taskProgressBar = 2131230738;
			
			// aapt resource value: 0x7f08000c
			public const int textView1 = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int titleText = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int toolbar = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int usernameText = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Advice = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AdviceListItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PreMain = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Settings = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int TaskListItem = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Tasks = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int toolbar = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int TopMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
